### ISSUE TITLE
Need a default process function

### ISSUE THREAD

**Issue by thdxr** [ironbay/tunk#1]
https://github.com/AlanRice93/tunk/blob/f4783d8f49e04429a9c6a4f3bfc821dd2e8891c3/lib/tunk.ex#L28

Sometimes this doesn't match.  GCP sends other messages not handled, need a process function that catches them.

**Comment by vaprdev** [comment]
Great idea thdxr! 

https://github.com/AlanRice93/tunk/commit/89779349647b1df2716661309c08dcb25e5f7a5d

Closing this issue for now.
